sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=lint
    - python: "3.7"
      env: TOXENV=py37
cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox coveralls
language: python
script: tox
after_success: coveralls
